workshop/routes/web.php
<?php
Route::get('/', function () {
    return view('welcome');
});

Route::get('/home/{user_id}', "HomeController@index");
Route::get('/student/{student_id}', "HomeController@list");

workshop/app/Classroom.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Classroom extends Model
{
    protected $fillable = [
    	"name", "shift"
    ];

    public function getFullNameAttribute() {
    	return $payment * 0.15;
    }
}

workshop/app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $dates = [""];
    protected $fillable = [
    	"classroom_id", "name", "uuid"
    ];

    public function classroom() {
    	return $this->belongsTo("\App\Classroom");
    }
}

workshop/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

workshop/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

workshop/app/Http/Controllers/HomeController.php
<?php

// app/Http/Controllers

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Student;
use App\Classroom;

class HomeController extends Controller
{
    public function index(Request $request, $user_id) {
    	// $classroom = ClassRoom::create([
    	// 	"name" => "M220",
    	// 	"shift" => "2",
    	// 	"id" => 30
    	// ]);

    	$studend = Student::create([
    		"classroom_id" => 1,
    		"name" => "João",
    		"uuid" => "A320-TI-2017"
    	]);

    	return view("home", [
    		"user_name" => "Pedro Paulo",
    		"user_id" => $user_id,
    		"classroom" => Classroom::find(1),
    	]);
    }

    public function list() {
    	$student = Student::with('classroom')->find(1);
    	return view('student', ["student" => $student]);
    }
}

workshop/resources/views/home.blade.php
@extends("layout.master")

@section("title")
	@parent - Home Page
@endsection

@section("main-content")
	<div class="row">
		<div class="col-xs-12">
			<h1>Workshop Laravel</h1>
			<p>Conteúdo</p>
			<p>Olá, {{$user_name}}</p>
			<p>Seu id é: {{$user_id}}</p>
			<p>A classe criada foi:</p>
			<ul>
				<li>{{$classroom->id}}</li>
				<li>{{$classroom->name}}</li>
				<li>{{$classroom->shift}}</li>
			</ul>
		</div>
	</div>
</div>
@endsection

workshop/resources/views/layout/master.blade.php
@section("title")
Workshop Laravel
@endsection

@section("head-scripts")
  <link href="{{asset("css/app.css")}}" rel="stylesheet">

  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
@endsection

@section("bottom-scripts")
  {{-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script> --}}
  <script src="{{asset("js/app.js")}}"></script>
  <script src="{{asset("js/custom.js")}}"></script>
@endsection

@section("main-content")

@endsection

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      @yield("title")
    </title>

    @yield("head-scripts")
</head>
  <body>
    <div class="container" id="app">
      @yield("main-content")
    </div>
    @yield("bottom-scripts")
  </body>
</html>

workshop/resources/views/student.blade.php
@extends("layout.master")

@section("title")
	@parent - Home Page
@endsection

@section("main-content")
	<div class="row">
		<div class="col-xs-12">
			<h1>Workshop Laravel</h1>
			<p>Conteúdo</p>
			<p>Olá, {{$student->name}}</p>
			<p>Seu id é: {{$student->id}}</p>
			<p>A sua classe é:</p>
			<ul>
				<li>{{$student->classroom->id}}</li>
				<li>{{$student->classroom->full_name}}</li>
				<li>{{$student->classroom->shift}}</li>
			</ul>
		</div>
	</div>
</div>
@endsection